config/routes.rb
Rails.application.routes.draw do
  resources :reserva_salas

  resources :salas

  resources :reservas

  devise_for :usuarios
  root :to => 'inicio#index'
  get 'inicio/index'

end

app/models/reserva.rb
class Reserva < ActiveRecord::Base
  belongs_to :sala

  has_many :reserva_sala
  has_many :salas, :through => :reserva_sala

  validates :dia, presence: true
  validates :hora, presence: true



end

app/models/reserva_sala.rb
class ReservaSala < ActiveRecord::Base
  belongs_to :reservas
  belongs_to :salas

  validates :reservas, presence: true
  validates :salas, presence: true


end

app/models/sala.rb
class Sala < ActiveRecord::Base
  belongs_to :reservas

  has_many :reserva_sala
  has_many :reservas, :through => :reserva_sala

  validates :salaFull, presence: true
  validates :salaMedia, presence: true
  validates :salaBasica, presence: true

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         # Confirmamos el email y validamos que no sean vacios con presence
         # mostramos el mensaje de error con message
         #validates :email , presence: true , confirmation: true
         #validates :email_confirmation, presence: { message: " es requerido"}

         # Validamos en una expresion regular nuestro email
         #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
         #validates :email, format: { :with => VALID_EMAIL_REGEX , message: "El formato del correo es invalido" }

         # Validamos que el identificador tenga entre 8 a 12 caracteres
         #validates :identificador, length: { in: 8..12 , message: "debe tener entre 8 y 12 caracteres"}

         # Validamos que el identificador solo sea numerico
         #validates :identificador, numericality: { only_integer: true }

         # Validamos que el email sea unico
         #validates :email, uniqueness: {case_sensitive: false ,message: "ya esta registrado"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
  end
end

app/controllers/reserva_salas_controller.rb
class ReservaSalasController < ApplicationController
  before_action :set_reserva_sala, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!, except: [:show, :index]
  respond_to :html

  def index
    @reserva_salas = ReservaSala.all
    respond_with(@reserva_salas)
  end

  def show
    respond_with(@reserva_sala)
  end

  def new
    @reserva_sala = ReservaSala.new
    respond_with(@reserva_sala)
  end

  def edit
  end

  def create
    @reserva_sala = ReservaSala.new(reserva_sala_params)
    @reserva_sala.save
    respond_with(@reserva_sala)
  end

  def update
    @reserva_sala.update(reserva_sala_params)
    respond_with(@reserva_sala)
  end

  def destroy
    @reserva_sala.destroy
    respond_with(@reserva_sala)
  end

  private
    def set_reserva_sala
      @reserva_sala = ReservaSala.find(params[:id])
    end

    def reserva_sala_params
      params.require(:reserva_sala).permit(:reserva_id, :sala_id)
    end
end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  before_action :set_reserva, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!, except: [:show, :index]
  respond_to :html

  def index
    @reservas = Reserva.all
    respond_with(@reservas)
  end

  def show
    respond_with(@reserva)
  end

  def new
    @reserva = Reserva.new
    respond_with(@reserva)
  end

  def edit
  end

  def create
    @reserva = Reserva.new(reserva_params)
    @reserva.save
    respond_with(@reserva)
  end

  def update
    @reserva.update(reserva_params)
    respond_with(@reserva)
  end

  def destroy
    @reserva.destroy
    respond_with(@reserva)
  end


  private
    def set_reserva
      @reserva = Reserva.find(params[:id])
    end

    def reserva_params
      params.require(:reserva).permit(:dia, :hora)
    end
end

app/controllers/salas_controller.rb
class SalasController < ApplicationController
  before_action :set_sala, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!, except: [:show, :index]
  respond_to :html

  def index
    @salas = Sala.all
    respond_with(@salas)
  end

  def show
    respond_with(@sala)
  end

  def new
    @sala = Sala.new
    respond_with(@sala)
  end

  def edit
  end

  def create
    @sala = Sala.new(sala_params)
    
    respond_with(@sala)
  end

  def update
    @sala.update(sala_params)
    respond_with(@sala)
  end

  def destroy
    @sala.destroy
    respond_with(@sala)
  end

  def show
    @reservas = @sala.reserva.all
  end


  private
    def set_sala
      @sala = Sala.find(params[:id])
    end

    def sala_params
      params.require(:sala).permit(:salaFull, :salaMedia, :salaBasica)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/reserva_salas_helper.rb
module ReservaSalasHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/helpers/salas_helper.rb
module SalasHelper
end

app/views/inicio/index.html.erb
<h1>"BIENVENIDO A ESTUDIO MELÓDICO" </h1>

<p>EL FUTURO DE TUS MELODÍAS GRABADAS EN MANOS DE MAESTROS</p>
<br>
<p> *RESERVAS ON LINE </p>
<br>
<p> HORARIO DE ATENCIÓN: LUNES A DOMINGO DE 10.00 A 24.00 HRS </p>
<br>
<p> ESTACIONAMIENTOS PROPIO, CAFETERIA, SALÓN DE DESCANSO y SALÓN DE JUEGOS DE VIDEO GRATIS </p>
<br>
<p> CONSULTAS POR PLANES DE GRABACION DE DISCOGRAFÍA </p>
<br>
<p> TELÉFONO: 02-2222-2222 </p>
<p> WHATSAPP: +56 9 2222-2222 </p>
<p> EstudioMelodico@ppbass.cl </p>
<p> FACEBOOK ESTUDIOMELICO </p>
<p> @ESTUDIOMELODICO </p>


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<p> Diseño creado por Ppbass </p>
</br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EstudioMelodico</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
</head>
<body>

<%= render 'shared/navbar' %>
<body style="background:##00695c">

<div class="container">


<%= yield %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= link_to 'Volver Inicio', root_path %>
</div>
</body>
</html>

app/views/reserva_salas/_form.html.erb
<%= form_for(@reserva_sala) do |f| %>
  <% if @reserva_sala.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reserva_sala.errors.count, "error") %> prohibited this reserva_sala from being saved:</h2>

      <ul>
      <% @reserva_sala.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reserva_id %><br>
    <%= f.text_field :reserva_id %>
  </div>
  <div class="field">
    <%= f.label :sala_id %><br>
    <%= f.text_field :sala_id %>
  </div>

  <%= f.hidden_field :usuario_id, :value => current_usuario.id %>
  <div class="actions">
    <%= f.submit "Crear reserva" %>
  </div>
<% end %>

app/views/reserva_salas/edit.html.erb
<h1>Editar</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @reserva_sala %> |
<%= link_to 'Atras', reserva_salas_path %>

app/views/reserva_salas/index.html.erb
<h3>Arriendo de instrumentos</h3>

<table>
  <thead>
    <tr>
      <th>Guitarra Fender Valor $10.000 x hora</th>
      <tr>
      <th>Guitarra Gibson Valor $9.000  x hora</th>
      <tr>
      <th>Bajo Fender     Valor $5.000  x hora</th>
      <tr>
      <th>Bajo Ibanez     Valor $4.500  x hora</th>
      <tr>
      <th>Platillos       Valor $2.000  x hora</th>
      <tr>
      <th>Baquetas        Valor $1.000  x hora</th>
      <tr>
      <th>Percusión       Valor $2.000  x hora</th>
      <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reserva_salas.each do |reserva_sala| %>
      <tr>
        <td><%= reserva_sala.reserva.dia %></td>
        <td><%= reserva_sala.sala %></td>
        <td><%= link_to 'Mostrar', reserva_sala %></td>
        <td><%= link_to 'Editar', edit_reserva_sala_path(reserva_sala) %></td>
        <td><%= link_to 'Eliminar', reserva_sala, method: :delete, data: { confirm: '¿Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Crear reserva', new_reserva_path %>
<br>
<br>
<br>

app/views/reserva_salas/new.html.erb
<h1>Nueva </h1>

<%= render 'form' %>

<%= link_to 'Atrás', reserva_salas_path %>

app/views/reserva_salas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reserva:</strong>
  <%= @reserva_sala.reserva %>
</p>

<p>
  <strong>Sala:</strong>
  <%= @reserva_sala.sala %>
</p>

<%= link_to 'Edit', edit_reserva_sala_path(@reserva_sala) %> |
<%= link_to 'Back', reserva_salas_path %>

app/views/reservas/_form.html.erb
<%= form_for(@reserva) do |f| %>
  <% if @reserva.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reserva.errors.count, "error") %> prohibited this reserva from being saved:</h2>

      <ul>
      <% @reserva.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dia %><br>
    <%= f.date_select :dia %>
  </div>
  <div class="field">
    <%= f.label :hora %><br>
    <%= f.number_field :hora %>
  </div>
  <div class="actions">
    <%= f.submit "Crear reserva" %>
  </div>
<% end %>

app/views/reservas/edit.html.erb
<h1>Editar reserva</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @reserva %> |
<%= link_to 'ATRÁS', reservas_path %>

app/views/reservas/index.html.erb
<h3>Reservas agendadas</h3>

<table class = "table">

  <thead>
    <tr>
      <th>DÍA</th>

      <th>HORA</th>

      </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservas.each do |reserva| %>
      <tr>
        <td><%= reserva.dia %></td>
        <td><%= reserva.hora %></td>
        <td><%= link_to 'Mostrar', reserva %></td>
        <td><%= link_to 'Editar', edit_reserva_path(reserva) %></td>
        <td><%= link_to 'Eliminar', reserva, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Crear reserva', new_reserva_path %>

app/views/reservas/new.html.erb
<h2>Reserva de sala</h2>
<h5>SELECCIONE FECHA Y HORAS DE RESERVAS </h5>
<h8>NO DEBE DEJAR CAMPOS EN BLANCO</h8>

<%= render 'form' %>

<%= link_to 'ATRÁS', reservas_path %>

app/views/reservas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dia:</strong>
  <%= @reserva.dia %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @reserva.hora %>
</p>





<br>

<%= link_to 'Editar', edit_reserva_path(@reserva) %> |
<%= link_to 'ATRÁS', reservas_path %>

app/views/salas/_form.html.erb
<%= form_for(@sala) do |f| %>
  <% if @sala.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sala.errors.count, "error") %> prohibited this sala from being saved:</h2>

      <ul>
      <% @sala.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :salaFull %><br>
    <%= f.text_field :salaFull %>
  </div>
  <div class="field">
    <%= f.label :salaMedia %><br>
    <%= f.text_field :salaMedia %>
  </div>
  <div class="field">
    <%= f.label :salaBasica %><br>
    <%= f.text_field :salaBasica %>
  </div>
  <div class="actions">
    <%= f.submit "Nueva sala" %>
  </div>
<% end %>

app/views/salas/edit.html.erb
<h1>Editar sala</h1>

<%= render 'form' %>

<%= link_to 'Show', @sala %> |
<%= link_to 'Back', salas_path %>

app/views/salas/index.html.erb
<h3>Descripción de salas</h3>

<table class = "table">
  <thead>
    <tr>
      <th>SALA FULL</th>
      <th>Equipos completos de audio, aire acondicionado, luz natural. Valor $10.000 x hora</th>
      <tr>
      <th>SALA MEDIA</th>
      <th>Equipos: 3 amplificadores de guitarra, 1 amplificador de bajo, 3 micrófono. Valor $7.000</th>
      <tr>
      <th>SALA BASICA</th>
      <th>Equipos: 2 amplificadores de guitarra, 1 amplificador de bajo, 1 micrófono. Valor $5.000</th>
      <tr>
      <th>Arriendo de instrumentos valor $3.000 x hora</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salas.each do |sala| %>
      <tr>
        <td><%= sala.salaFull %></td>
        <td><%= sala.salaMedia %></td>
        <td><%= sala.salaBasica %></td>
        <td><%= link_to 'Ver', sala %></td>
        <td><%= link_to 'Editar', edit_sala_path(sala) %></td>
        <td><%= link_to 'Eliminar', sala, method: :delete, data: { confirm: '¿Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Crear reserva', new_reserva_path %>

<br>
<br>
<br>
</br>

app/views/salas/new.html.erb
<h1>Nueva sala</h1>

<%= render 'form' %>

<%= link_to 'Atrás', salas_path %>

app/views/salas/show.html.erb
<p id="notice"><%= notice %></p>

<h2> Reservas asociadas: </h2>
<% @reservas.each do |reserva| %>

<strong>Hora tomada : </strong>
<%= reserva.hora %>
<br>
</br>
<p>
  <strong>Salafull:</strong>
  <%= @sala.salaFull %>
</p>

<p>
  <strong>Salamedia:</strong>
  <%= @sala.salaMedia %>
</p>

<p>
  <strong>Salabasica:</strong>
  <%= @sala.salaBasica %>
</p>



<% end %>

<br>



<%= link_to 'Edit', edit_sala_path(@sala) %> |
<%= link_to 'Back', salas_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
<a class="navbar-brand" href="<%=root_path%>">Home</a>
    </div>
<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
                <li><a href="<%=salas_path%>">SALAS</a></li>
                <li><a href="<%=reservas_path%>">RESERVAS</a></li>
                <li><a href="<%=reserva_salas_path%>">ARRIENDO DE INSTRUMENTOS</a></li>

        </ul>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">

            <% if usuario_signed_in? %>

            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if usuario_signed_in? %>
            <li><a> <%= current_usuario.email %> </a></li>
              <li><a href="<%= edit_usuario_registration_path(current_usuario) %>">Editar Perfil</a></li>
              <li><a href="<%= destroy_usuario_session_path %>", data-method="delete">Cerrar Sesión</a></li>
            <% else %>
              <li><a href="<%= new_usuario_session_path %>">Ingresar</a></li>
              <li><a href="<%= new_usuario_registration_path %>">Registrarse</a></li>
            <% end %>
          </ul>
        </div></li><!-- /.navbar-collapse -->
</nav>
<style>
th{
padding: 20px;
}
</style>
<style>
body {background-color:lightgray}
h1   {color:#757575}
p    {color:#37474f}
</style>
</nav>